[package]
name = "tokio-util"
# When releasing to crates.io:
# - Remove path dependencies
# - Update doc url
#   - Cargo.toml
# - Update CHANGELOG.md.
# - Create "tokio-util-0.6.x" git tag.
version = "0.6.5"
edition = "2018"
authors = ["Tokio Contributors <team@tokio.rs>"]
license = "MIT"
repository = "https://github.com/tokio-rs/tokio"
homepage = "https://tokio.rs"
documentation = "https://docs.rs/tokio-util/0.6.5/tokio_util"
description = """
Additional utilities for working with Tokio.
"""
categories = ["asynchronous"]

[features]
# No features on by default
default = []

# Shorthand for enabling everything
full = ["codec", "compat", "io", "time", "net", "rt"]

net = ["tokio/net"]
compat = ["futures-io",]
codec = []
time = ["tokio/time","slab"]
io = []
rt = ["tokio/rt"]

__docs_rs = ["futures-util"]

[dependencies]
tokio = { version = "1.0.0", features = ["sync"] }

bytes = "1.0.0"
futures-core = "0.3.0"
futures-sink = "0.3.0"
futures-io = { version = "0.3.0", optional = true }
futures-util = { version = "0.3.0", optional = true }
log = "0.4"
pin-project-lite = "0.2.0"
slab = { version = "0.4.1", optional = true } # Backs `DelayQueue`

[dev-dependencies]
tokio = { version = "1.0.0", features = ["full"] }
tokio-test = { version = "0.4.0" }
tokio-stream = { version = "0.1" }

async-stream = "0.3.0"
futures = "0.3.0"
futures-test = "0.3.5"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[[test]]
name = "codecs"
path = "tests/codecs.rs"
required-features = ["codec"]

[[test]]
name = "length-delimited"
path = "tests/length_delimited.rs"
required-features = ["codec"]

[[test]]
name = "framed"
path = "tests/framed.rs"
required-features = ["codec"]

[[test]]
name = "framed-write"
path = "tests/framed_write.rs"
required-features = ["codec"]

[[test]]
name = "framed-read"
path = "tests/framed_read.rs"
required-features = ["codec"]

[[test]]
name = "udp"
path = "tests/udp.rs"
required-features = ["net"]

[[test]]
name = "io-reader-stream"
path = "tests/io_reader_stream.rs"
required-features = ["io"]

[[test]]
name = "io-stream-reader"
path = "tests/io_stream_reader.rs"
required-features = ["io"]
